roles:
  - src: https://github.com/mrlesmithjr/ansible-passenger.git
  - name: ansible-rails_app
    src: https://github.com/infraoptics/ansible-rails_app.git
    version: ubuntu_modifications
  - name: geerlingguy.apache
  - name: geerlingguy.postgresql
  - name: zzet.rbenv
  - name: ansible-role-rbenv_users
    src: https://github.com/DeepOps/ansible-role-users
