# from galaxy
- src: tulibraries.ansible_role_passenger_apache
- src: tulibraries.ansible_rails_app
- src: geerlingguy.apache
- src: zzet.rbenv
- src: https://github.com/DeepOps/ansible-role-users
- src: https://github.com/engonzal/ansible_role_package
